### ISSUE TITLE
Update broke styling

### ISSUE THREAD

**Issue by DellCliff** [flathub/org.strawberrymusicplayer.strawberry#65]
Update https://github.com/flathub/org.strawberrymusicplayer.strawberry/commit/99aa949fa2a0cae762d4a2a4d4923cf5c52a91b6 broke styling on Gnome platforms.

The issue is `org.kde.Platform` 6.6. There is no `org.kde.PlatformTheme.QGnomePlatform` 6.6 available on flathub, as far as I am aware. `org.kde.Platform` 6.5 works as intended, as there is `org.kde.PlatformTheme.QGnomePlatform` 6.5 available on flathub.

Possible solutions: Either revert to `org.kde.Platform` 6.5 or make `org.kde.PlatformTheme.QGnomePlatform` 6.6 available on flathub.

**Comment by Zishan-Rahman** [comment]
> Update [99aa949](https://github.com/flathub/org.strawberrymusicplayer.strawberry/commit/99aa949fa2a0cae762d4a2a4d4923cf5c52a91b6) broke styling on Gnome platforms.
> 
> The issue is `org.kde.Platform` 6.6. There is no `org.kde.PlatformTheme.QGnomePlatform` 6.6 available on flathub, as far as I am aware. `org.kde.Platform` 6.5 works as intended, as there is `org.kde.PlatformTheme.QGnomePlatform` 6.5 available on flathub.
> 
> Possible solutions: Either revert to `org.kde.Platform` 6.5 or **make `org.kde.PlatformTheme.QGnomePlatform` 6.6 available on flathub.**

@DellCliff (sorry for the ping) [I recently opened a PR for `org.kde.PlatformTheme.QGnomePlatform` that _should_ take care of this](https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/pull/19). Once a new branch is created and pushed to Flathub, these GNOME theming issues _should_ get resolved.

**Comment by Zishan-Rahman** [comment]
My PR has now been merged, and [a new 6.6 branch was literally _just_ created](https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/tree/branch/6.6). Since it was only _just_ made, however, it _will_ take some time (approximately a few hours or so) for the new branch to actually get pushed to Flathub. You'll be able to find out when it's made it to Flathub if running `flatpak remote-info --system flathub org.kde.PlatformTheme.QGnomePlatform//6.6` on the command line _doesn't_ throw an error, after which you _should_ be able to install it on your computer and then the styling should work again.

**Comment by DellCliff** [comment]
Fixed! That was insanely fast. Thanks, very much appreciated.
